### PR TITLE
Merge changes for version 2.5.0 dev

### PR DESCRIPTION
**Pull request by tobolar**

### CODE REVIEW

**Review by HansOlsson — CHANGES_REQUESTED** [review]
Modelica_LinearSystems2.Controller.Examples.SimpleControlledDrive no longer simulates in Dymola.
The error message is:
Incompatible sizes for variable and its definition equation;
filter.discretePart.x_start = filter.x_start
I have not been able to track down the specific change, and it's likely that there are more problematic models.

**Comment by tobolar** [comment]
@HansOlsson I will check it.

**Comment by tobolar** [comment]
The problem seems to be in the evaluation of `M_LS2.ZerosAndPoles.Conversion.toMatrices()` within `M_LS2.Controller.ZerosAndPoles` which is inherited by `M_LS2.Controller.Filter` used in abovementioned example.

Here, `nx` is evaluated using `nx=size(system.d1,1) + 2*size(system.d2,1)` while the `discretePart`'s nx is evaluated using matrix ABCD which is input by `M_LS2.ZerosAndPoles.Conversion.toMatrices(system)` (line 12 in M_LS2.Controller.ZerosAndPoles). In fact, they both shall be deliver the same integer - which was the case so far.

I have also analysed flat code. Only relevant difference I found is as follows (both generated by Dymola 2020x)
- Modelica flat code of MSL 3.2.3, M_LS2 2.3.5:
   ```
   parameter Real filter.discretePart.ABCD[:, :] = Modelica_LinearSystems2.ZerosAndPoles.Conversion.toMatrices(filter.system);
   parameter Real filter.discretePart.A[:, :] = filter.discretePart.ABCD[1:end-1, 1:end-1];
   parameter Real filter.discretePart.B[:, 1] = filter.discretePart.ABCD[1:end-1, end:end];
   parameter Real filter.discretePart.C[1, :] = filter.discretePart.ABCD[end:end, 1:end-1];```

- Modelica flat code of MSL 4.0.0, M_LS2 2.5.0-dev:
   ```
   parameter Real filter.discretePart.ABCD[2, 2](start = [1, 1; 1, 1]) = Modelica_LinearSystems2.ZerosAndPoles.Conversion.toMatrices(filter.system);
   parameter Real filter.discretePart.A[:, :] = filter.discretePart.ABCD[1:end-1, 1:end-1];
   parameter Real filter.discretePart.B[1, 1] = [filter.discretePart.ABCD[1, 2]];
   parameter Real filter.discretePart.C[1, 1] = [filter.discretePart.ABCD[2, 1]];```

@HansOlsson Any idea how to proceed?

**Comment by tobolar** [comment]
> 
> 
> The problem seems to be in the evaluation of `M_LS2.ZerosAndPoles.Conversion.toMatrices()` within `M_LS2.Controller.ZerosAndPoles` which is inherited by `M_LS2.Controller.Filter` used in abovementioned example.
> 
> Here, `nx` is evaluated using `nx=size(system.d1,1) + 2*size(system.d2,1)` while the `discretePart`'s nx is evaluated using matrix ABCD which is input by `M_LS2.ZerosAndPoles.Conversion.toMatrices(system)` (line 12 in M_LS2.Controller.ZerosAndPoles). In fact, they both shall deliver the same integer - which was the case so far.
> 
> I have also analysed the flat code. Only relevant difference I found is as follows (both generated by Dymola 2020x)
> 
>     * Modelica flat code of MSL 3.2.3, M_LS2 2.3.5:
>       ```
>       parameter Real filter.discretePart.ABCD[:, :] = Modelica_LinearSystems2.ZerosAndPoles.Conversion.toMatrices(filter.system);
>       parameter Real filter.discretePart.A[:, :] = filter.discretePart.ABCD[1:end-1, 1:end-1];
>       parameter Real filter.discretePart.B[:, 1] = filter.discretePart.ABCD[1:end-1, end:end];
>       parameter Real filter.discretePart.C[1, :] = filter.discretePart.ABCD[end:end, 1:end-1];```
>       ```
> 
>     * Modelica flat code of MSL 4.0.0, M_LS2 2.5.0-dev:
>       ```
>       parameter Real filter.discretePart.ABCD[2, 2](start = [1, 1; 1, 1]) = Modelica_LinearSystems2.ZerosAndPoles.Conversion.toMatrices(filter.system);
>       parameter Real filter.discretePart.A[:, :] = filter.discretePart.ABCD[1:end-1, 1:end-1];
>       parameter Real filter.discretePart.B[1, 1] = [filter.discretePart.ABCD[1, 2]];
>       parameter Real filter.discretePart.C[1, 1] = [filter.discretePart.ABCD[2, 1]];```
>       ```
> 
> 
> @HansOlsson Any idea how to proceed?

I now removed false initialization of the ABCD matrix (see 50e0ce19adb294c2bb3fafe5eca3f16bdab45dc2) which was the cause.

**Pull request merged**
