### PR TITLE
New version

### PR DESCRIPTION
**Pull request by HansOlsson**
Adapted for new MSL version.
I believe at least the following should also be handled: #64
The some other open issues could also be handled.

### CODE REVIEW

**Comment by HansOlsson** [comment]
> The year of copyright shall by updated as well.
> And even more important are the release notes which are missing completelly. Would you prepare it?

I could do that (the release note will be brief since there were no major changes).

However, it would be good if #64 was resolved - and I think it would be odd if I changed that.

**Comment by HansOlsson** [comment]
I updated release notes.
But on second thought I believe that you have to change copyright year and #64, and possibly #33.

**Comment by HansOlsson** [comment]
Regarding the license issue: `Modelica_LinearSystems2.Controller.Internal.random` contains `<a href=\"modelica://Modelica.UsersGuide.ModelicaLicense2\">ModelicaLicense2</a>`

**Comment by beutlich** [comment]
I wonder why this PR targets the master branch if there alread is a branch [version_2.3.5](https://github.com/modelica/Modelica_LinearSystems2/tree/version_2.3.5), that is 47 commits ahead and 8 commits behind master.

**Comment by HansOlsson** [comment]
> I wonder why this PR targets the master branch if there already is a branch version_2.3.5, that is 47 commits ahead and 8 commits behind master.

Well, I totally missed that branch (and also that comment).

However, the status of that branch is not clear - in particular whether that branch is "ready" or not.

To me a version of Modelica_LinearSystem2 compatible with released version of MSL should be available now. I assume version_2.3.5 could be renamed to 2.3.6 as well (or 2.4 if even larger changes), or maybe version_2.3.5 is ready as is, or maybe the version for MSL 3.2.3 should be 2.3.4.1 instead.

**Comment by tobolar** [comment]
End of last year, I worked a lot on https://github.com/modelica/Modelica_LinearSystems2/tree/version_2.3.5 in order to adapt to changes planed for MSL 3.2.3. The biggest change ist the usage of standard Complex operator instead of Modelica_LinearSystems2.Math.Complex (incl. version conversion script). I have also always tryed to check the classes with Dymola.

So from my point of view the branch "version_2.3.5" ist significantly better candidate then current master. But I must admit I have not tested that version with MSL v3.2.3 so far.

@HansOlsson Do you have some routines to test that branch in current Dymola?

Concerning version number: either v2.4.0 or (maybe better) v3.0.0

**Comment by tobolar** [comment]
I have revised https://github.com/modelica/Modelica_LinearSystems2/tree/version_2.3.5  and am of the mind that it will take a bit time to merge it. So to enable Modelica_LinearSystems2 (depending on MSL v3.2.3) for users as soon as possible I prefer to release a maintenance version only. 

@HansOlsson I would change README.md in a separate PR. So please withdraw that file in your PR.

**Pull request merged**
