### PR TITLE
Package Types moved into Utilities.Types, see issue #13.

### PR DESCRIPTION
**Pull request by tobolar**
Conversion script added as well.

### CODE REVIEW

**Comment by dietmarw** [comment]
@tobolar Something with your line ending settings seems to be strange since all your changes change *all* files rather only the actual changes of the lines.

**Comment by sjoelund** [comment]
Perhaps set `*.mo eol=native` in gitattributes to force the line-endings?

**Comment by tobolar** [comment]
@sjoelund Thank's, I'll do it.

**Comment by dietmarw** [comment]
`* -text ` setting should normally not touch the line endings. But try it.

**Comment by dietmarw** [comment]
you might revert your earlier commits again and try again to not loose the actual changes right now.

**Comment by tobolar** [comment]
This will probably imply a lot of work since Dymola changes high portion of code as well.

**Comment by dietmarw** [comment]
Dymola ... sigh

**Comment by sjoelund** [comment]
Maybe I should advertise that OMEdit preserves whitespace even when dragging and dropping components in a file, setting parameters, etc. It works rather well by now (1.11.0 beta); I used it for editing Modelica_DeviceDrivers code and got rather good commit diffs.

**Comment by tobolar** [comment]
Unfortunately, I have no experience with OpenModelica so far. Maybe its a good time to try it now. ;-)

**Pull request merged**
